# Generated by Django 4.0.4 on 2023-01-11 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='membership_points',
            new_name='curr_membership_points',
        ),
    ]
