# Generated by Django 4.0.4 on 2022-09-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_membership_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='google_drive_folder_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
