# Generated by Django 4.0.4 on 2023-01-11 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_membership_points_customuser_curr_membership_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='curr_membership_points',
            new_name='membership_points',
        ),
    ]
