# Generated by Django 4.0.4 on 2023-01-11 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_curr_membership_points_customuser_membership_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterMembershipStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(default='', max_length=20)),
                ('membership_points', models.IntegerField(default=0)),
                ('membership_tier', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
