# Generated by Django 4.0.4 on 2022-09-02 05:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_meeting_google_drive_folder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='meeting',
            name='organizers',
            field=models.ManyToManyField(related_name='meeting_organizers', related_query_name='meeting_organizers', to=settings.AUTH_USER_MODEL),
        ),
    ]
