# Generated by Django 4.0.4 on 2022-08-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='membership_tier',
            field=models.CharField(blank=True, choices=[('P', 'Platinum'), ('G', 'Gold'), ('S', 'Silver'), ('B', 'Bronze'), ('N', 'None')], default='N', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='year_in_school',
            field=models.CharField(blank=True, choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=12, null=True),
        ),
    ]
