# Generated by Django 4.0.4 on 2023-01-11 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_semestermembershipstorage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_of_term', models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], default='Fall', max_length=20)),
                ('year', models.CharField(default='2022', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='semestermembershipstorage',
            name='semester_name',
        ),
        migrations.AddField(
            model_name='event',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.semester'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.semester'),
        ),
        migrations.AddField(
            model_name='semestermembershipstorage',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.semester'),
        ),
    ]
