# Generated by Django 4.0.4 on 2022-08-18 23:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_customuser_membership_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(related_name='event_organizers', related_query_name='event_organizers', to=settings.AUTH_USER_MODEL),
        ),
    ]
