# Generated by Django 4.0.4 on 2022-08-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_event_organizers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='membership_tier',
            field=models.CharField(blank=True, choices=[('Platinum', 'Platinum'), ('G', 'Gold'), ('S', 'Silver'), ('B', 'Bronze'), ('None', 'None')], default='N', max_length=12, null=True),
        ),
    ]
